# Count occurences of a property
#
PREFIX dct: <http://purl.org/dc/terms/>
#
select (str(count(*)) as ?count) ?property
where {
  values ( ?property ) {
    ( dct:creator )
  }
  ?s ?property [] .
}
group by ?property

