# Get all subclasses of a wikidata class
#
PREFIX wd: <http://www.wikidata.org/entity/> 
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
#
select distinct ?item ?label
where {
  values ( ?class ) {
    # default: organization
    ( wd:Q43229 )
  }
  ?item wdt:P279+ ?class .
  optional {
    ?item rdfs:label ?label
    filter (lang(?label) = "en").
  }
}
