# Get the industry by mapping to SK classification
#
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX esco: <http://data.europa.eu/esco/model#>
PREFIX hint: <http://www.bigdata.com/queryHints#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX zbwext: <http://zbw.eu/namespaces/zbw-extensions/>
#
select ?wd ?main ?industry ?industryLabel ?list ("list" as ?listLabel)
where {
  ##hint:Query hint:optimizer "None" .
  {
    select ?notation ?main ?industry 
    where {
      # has to be adapted in the language service clause, too
      values ( ?language ) {
        ( "de" )
      }
      # SK industry category system to WD mapping, with main sections added
      values ( ?notation ?industry ?mainDe ?mainEn ) {
        ( "SEC-01" undef "Landwirtschaft" "Agriculture" )
        ( "SEC-01001" wd:Q29584242 undef undef )
        ( "SEC-01010" wd:Q1283714 undef undef )
        ( "SEC-01020" wd:Q80962 undef undef )
        ( "SEC-02" undef "Forstwirtschaft" "Forrestry" )
        ( "SEC-02000" wd:Q18218474 undef undef )
        ( "SEC-03" undef "Fischerei" "Fishery" )
        ( "SEC-03000" wd:Q180538 undef undef )
        ( "SEC-04" undef "Energie- und Wasserwirtschaft" "Energy and Water Industries" )
        ( "SEC-04001" wd:Q107594896 undef undef )
        ( "SEC-04010" wd:Q29584213 undef undef )
        ( "SEC-04011" wd:Q29584657 undef undef )
        ( "SEC-04012" wd:Q48767813 undef undef )
        ( "SEC-04020" wd:Q474883 undef undef )
        ( "SEC-05" undef "Rohstoffwirtschaft und Bergbau" "Resource Sector and Mining" )
        ( "SEC-05001" wd:Q100251245 undef undef )
        ( "SEC-05010" wd:Q44497 undef undef )
        ( "SEC-05011" wd:Q12089268 undef undef )
        ( "SEC-05020" wd:Q29584253 undef undef )
        ( "SEC-06" undef "Industrie" "Industries" )
        ( "SEC-06001" wd:Q8148 undef undef )
        ( "SEC-06010" wd:Q1924906 undef undef )
        ( "SEC-06020" wd:Q107597925 undef undef )
        ( "SEC-06030" wd:Q107597958 undef undef )
        ( "SEC-06040" wd:Q1326885 undef undef )
        ( "SEC-06050" wd:Q107598010 undef undef )
        ( "SEC-06060" wd:Q207652 undef undef )
        ( "SEC-06061" wd:Q862571 undef undef )
        ( "SEC-06070" wd:Q1625796 undef undef )
        ( "SEC-06080" wd:Q107598107 undef undef )
        ( "SEC-06090" wd:Q107598157 undef undef )
        ( "SEC-06100" wd:Q29584265 undef undef )
        ( "SEC-06110" wd:Q107601662 undef undef )
        ( "SEC-06120" wd:Q107601756 undef undef )
        ( "SEC-06130" wd:Q56604576 undef undef )
        ( "SEC-06140" wd:Q392933 undef undef )
        ( "SEC-07" undef "Bauwirtschaft" "Construction Industry" )
        ( "SEC-07001" wd:Q100251750 undef undef )
        ( "SEC-07010" wd:Q29584305 undef undef )
        ( "SEC-08" undef "Handwerk" "Trade (Craft)" )
        ( "SEC-08001" wd:Q2207288 undef undef )
        ( "SEC-09" undef "Dienstleistungen" "Service Industries" )
        ( "SEC-09001" wd:Q7406919 undef undef )
        ( "SEC-10" undef "Handel" "Trade" )
        ( "SEC-10001" wd:Q601401 undef undef )
        ( "SEC-10010" wd:Q29584688 undef undef )
        ( "SEC-10020" wd:Q107602514 undef undef )
        ( "SEC-10030" wd:Q57262255 undef undef )
        ( "SEC-10040" wd:Q107602764 undef undef )
        ( "SEC-10050" wd:Q220695 undef undef )
        ( "SEC-10060" wd:Q178803 undef undef )
        ( "SEC-10070" wd:Q126793 undef undef )
        ( "SEC-11" undef "Gastgewerbe" "Hospitality Industry" )
        ( "SEC-11000" wd:Q100252087 undef undef )
        ( "SEC-12" undef "Verkehr und Tourismus" "Transport and Tourism" )
        ( "SEC-12001" wd:Q107603209 undef undef )
        ( "SEC-12010" wd:Q3565868 undef undef )
        ( "SEC-12020" wd:Q516739 undef undef )
        ( "SEC-12030" wd:Q29584313 undef undef )
        # manually inserted extra line for "Hafenwirtschaft (W12-031"
        ( "SEC-12031" wd:Q25382881 undef undef )
        ( "SEC-12040" wd:Q1757562 undef undef )
        ( "SEC-12050" wd:Q2072431 undef undef )
        ( "SEC-12060" wd:Q3997851 undef undef )
        ( "SEC-12070" wd:Q11630521 undef undef )
        ( "SEC-13" undef "Post und Telekommunikation" "Postal and Telecommunications Services" )
        ( "SEC-13001" wd:Q107605278 undef undef )
        ( "SEC-13010" wd:Q100316952 undef undef )
        ( "SEC-14" undef "Finanz- und Kreditwesen" "Financial Services and Banking" )
        ( "SEC-14001" wd:Q29584334 undef undef )
        ( "SEC-14010" wd:Q29585695 undef undef )
        ( "SEC-15" undef "Börsen und Wertpapierhandel" "Stock Markets" )
        ( "SEC-15000" wd:Q475000 undef undef )
        ( "SEC-16" undef "Versicherungswesen" "Insurance Industry" )
        ( "SEC-16000" wd:Q43183 undef undef )
        ( "SEC-17" undef "Immobilienwirtschaft" "Real Estate Services" )
        ( "SEC-17001" wd:Q29584338 undef undef )
        ( "SEC-17010" wd:Q2588161 undef undef )
        ( "SEC-20" undef "Forschungseinrichtungen" "Research Center" )
        ( "SEC-20000" wd:Q29584345 undef undef )
        ( "SEC-21" undef "Unternehmensdienstleistungen" "Business Services" )
        ( "SEC-21001" wd:Q25351891 undef undef )
        ( "SEC-21010" wd:Q63769412 undef undef )
        ( "SEC-21020" wd:Q37038 undef undef )
        ( "SEC-21030" wd:Q58891744 undef undef )
        ( "SEC-22" undef "Öffentlicher Sektor" "Public Sector" )
        ( "SEC-22000" wd:Q294217 undef undef )
        ( "SEC-23" undef "Nonprofit-Sektor" "Nonprofit Sector" )
        ( "SEC-23001" wd:Q1063076 undef undef )
        ( "SEC-23010" wd:Q71128408 undef undef )
        ( "SEC-24" undef "Bildungswesen" "Educational System" )
        ( "SEC-24001" wd:Q29584231 undef undef )
        ( "SEC-24010" wd:Q21028957 undef undef )
        ( "SEC-25" undef "Gesundheitswesen" "Health System" )
        ( "SEC-25000" wd:Q29584363 undef undef )
        ( "SEC-26" undef "Sozialwesen" "Social Welfare System" )
        ( "SEC-26000" wd:Q2306033 undef undef )
        ( "SEC-27" undef "Freizeitwirtschaft" "Leisure Industries" )
        ( "SEC-27000" wd:Q59308842 undef undef )
        ( "SEC-28" undef "Kultursektor" "Cultural Industries" )
        ( "SEC-28000" wd:Q59285259 undef undef )
        ( "SEC-29" undef "Medienwirtschaft" "Media Industries" )
        ( "SEC-29000" wd:Q56611639 undef undef )
        ( "SEC-30" undef "Informationswirtschaft" "Information Services" )
        ( "SEC-30000" wd:Q871337 undef undef )
        ( "SEC-32" undef "Abfallwirtschaft und Recycling" "Waste Management and Recycling" )
        ( "SEC-32001" wd:Q29584299 undef undef )
        ( "SEC-98" undef "Internationale Körperschaften" "International Organizations" )
        ( "SEC-98000" wd:Q107607934 undef undef )
      }
      bind(if(?language = 'en', ?mainEn, ?mainDe) as ?main)
    }
  }
  # link for company list per industry
  bind(strafter(str(?industry), str(wd:)) as ?industryQid)
  bind(uri(concat('http://zbw.eu/beta/sparql-lab/?endpoint=https://query.wikidata.org/sparql&queryRef=https://api.github.com/repos/zbw/sparql-queries/contents/wikidata/companies_pm20_by_industry.rq&industryQid=', ?industryQid)) as ?list)
  #
  optional {
    service wikibase:label {
      bd:serviceParam wikibase:language "de" .
    }
  }
}
order by ?notation

