# Get the industry and nace assignment from pm20
#
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX esco: <http://data.europa.eu/esco/model#>
PREFIX frapo: <http://purl.org/cerif/frapo/>
PREFIX hint: <http://www.bigdata.com/queryHints#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX zbwext: <http://zbw.eu/namespaces/zbw-extensions/>
#
select ?pm20Id ?pm20 ?pm20Label ?qid ?naceCode ?industry ##(concat('Q', str( min(?industryId) )) as ?industryQid)
where {
  hint:Query hint:optimizer "None" .
  #
  # all companies with country from PM20
  service <http://zbw.eu/beta/sparql/pm20/query> {
    ?pm20 a zbwext:CompanyFolder ;
          skos:prefLabel ?pm20Label ;
          dct:identifier ?pm20Id .
    optional {
      ?pm20 schema:industry ?industry .
      filter(lang(?industry) = 'en')
    }
    optional {
      ?pm20 esco:hasNACECode ?naceCode .
    }
  }
    
  # "main" items - exclude items linked with mapping relations
  ?statement ps:P4293 ?pm20Id .
  ?wd p:P4293 ?statement .
  filter (not exists {
      ?statement pq:P4390 [] .
    })
  bind(strafter(str(?wd), str(wd:)) as ?qid)
  #
  # exclude items with already existing country
##  filter(not exists {
##      ?wd wdt:P17 [] .
##    })
  #
##  optional {
##    ?industryWd wdt:P297 ?countryCode .
##    bind(xsd:integer(strafter(str(?industryWd), 'http://www.wikidata.org/entity/Q')) as ?industryId)
##  }
}
##group by ?pm20Id ?pm20 ?pm20Label ?qid ?countryCode
##order by ?pm20Id $industryId

