# Count the triples per graph
#
SELECT (str(?count) as ?tripleCount) ?graphName
WHERE {
  {
    # the default graph
    SELECT (count(?s) as ?count)
    WHERE {
      ?s ?p ?o 
    }
  } UNION {
    SELECT (count(?s) as ?count) ?graphName
    WHERE {
      GRAPH ?graphName {
        ?s ?p ?o 
      }
    }
    GROUP BY ?graphName
    ORDER BY desc(?count)
  }
}
