# Search concepts by text
#
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX text: <http://jena.apache.org/text#>
PREFIX gndo: <http://d-nb.info/standards/elementset/gnd#>
#
SELECT  ?concept ?prefName ?prefLabel
WHERE {
  VALUES ( ?query ) {
    ( "snower" )
  }
  ?concept text:query ?query ;
    gndo:preferredNameForThePerson|gndo:preferredNameForTheCorporateBody ?prefName ;
    skos:prefLabel ?prefLabel .
}
