# Autosuggest query for persons using a phrase index
#
PREFIX gndo:   <http://d-nb.info/standards/elementset/gnd#>
PREFIX text:   <http://jena.apache.org/text#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX zbwext: <http://zbw.eu/namespaces/zbw-extensions/>
#
select distinct ?pers (?name as ?persLabel) ?pref
where 
{
  # other search strings: "fischer,\\ peter*"
  ?pers text:query (skos:prefLabel "peter,\\ c*") ;
        gndo:preferredNameForThePerson ?name ;
        skos:prefLabel ?pref ;
        zbwext:econbizCount ?publicationCount
  .
}
order by desc(?publicationCount)
limit 10

