# create a mapping table from gndId to folder id
# For companies, there are 10 cases where one gndId maps to two folders.
# To make this work as Apache RewriteMap, use arbitrarily on of these.

PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
PREFIX zbwext: <http://zbw.eu/namespaces/zbw-extensions/>
#
select distinct ?gndId (max(?fid) as ?pm20Id)
where {
  ?pm20 gndo:gndIdentifier ?gndId .
  bind(strafter(str(?pm20), 'http://purl.org/pressemappe20/folder/') as ?fid)
  filter(strstarts($fid, 'co') || strstarts($fid, 'pe'))
}
group by ?gndId

