# All GND persons linked to ORCID
#
PREFIX gndo:   <https://d-nb.info/standards/elementset/gnd#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
#
select *
where {
  ?person a gndo:DifferentiatedPerson ;
          owl:sameAs ?orcid .
  filter(strstarts(str(?orcid), 'https://orcid.org/'))
  ?person gndo:preferredNameForThePerson ?personLabel .
}
order by ?personLabel
