# Corporate bodies by gnd subject categories classification
#
PREFIX gndsc: <http://d-nb.info/standards/vocab/gnd/gnd-sc#>
PREFIX gndo: <http://d-nb.info/standards/elementset/gnd#>
#
construct {
  ?corp gndo:gndSubjectCategory ?category ;
}
where {
  # to be replaced by category notations from categories.lst
  values ?categoryNotation {
    "10.2a"
  }
  bind(uri(concat("http://d-nb.info/standards/vocab/gnd/gnd-sc#", ?categoryNotation)) as ?category)
  ?corp a gndo:CorporateBody ;
        gndo:gndSubjectCategory ?category ;
        .
}
