# Persons by GND subject categories classification
#
PREFIX gndsc: <http://d-nb.info/standards/vocab/gnd/gnd-sc#>
PREFIX gndo: <http://d-nb.info/standards/elementset/gnd#>
#
construct {
  ?pers gndo:gndSubjectCategory ?category ;
}
where {
  # to be replaced by category notations from categories.lst
  values ?categoryNotation {
    "10.2dp"
  }
  bind(uri(concat("http://d-nb.info/standards/vocab/gnd/gnd-sc#", ?categoryNotation)) as ?category)
  ?pers a gndo:DifferentiatedPerson ;
        gndo:gndSubjectCategory ?category ;
        .
}
