prefix dcterms: <http://purl.org/dc/terms/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX zbwext: <http://zbw.eu/namespaces/zbw-extensions/>
#
# Number of descriptors by number of categories they are attached to
#
select ?categoryCount (str(count(*)) as ?descriptorCount)
where
{
  select ?descriptor (str(count(distinct ?category)) as ?categoryCount)
  where {
    ?descriptor a zbwext:Descriptor .
    ?descriptor skos:broader ?category .
    ?category a zbwext:Thsys .
  }
  group by ?descriptor
}
group by ?categoryCount
order by ?categoryCount

