# Search concepts by text (e.g., 'labour')
#
# Covers concepts from different (mapped) datasets,
# and, from STW, different subclasses of skos:Concept
#
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX text: <http://jena.apache.org/text#>
#
SELECT  ?concept ?prefLabel
WHERE {
  VALUES ( ?query ?language ) {
    ( "labour" "en" )
  }
  ?concept text:query ?query ;
    skos:prefLabel ?prefLabel .
  filter (lang(?prefLabel) = ?language)
}
