# Concepts related to 'market'
#
# Covers concepts from different (mapped) datasets,
# and, from STW, different subclasses of skos:Concept
#
PREFIX  text:   <http://jena.apache.org/text#>
PREFIX  skos:   <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
#
SELECT  ?concept ?prefLabel
WHERE {
  VALUES ( ?language ) {
    ( "en" ) 
  }
  ?concept text:query 'market' ;
    skos:prefLabel ?prefLabel .
  filter (lang(?prefLabel) = ?language)
}
