# all publications by an identified person with a certain name
# plus all publications by unindentified authors with that name
#
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
#
select distinct ?pub ?actor 
where {
  {
    # the one particular Christian Lambertz
    bind(<http://d-nb.info/gnd/1059126265> as ?actor)
    ?pub dct:creator  ?actor.
  } union {
    ?pub dct:creator [ rdfs:label "Lambertz, Christian" ] .
  }
}
