# all publications by an identified person "Fischer, Peter"
# plus all publications by unindentified authors named "Fischer, Peter"
#
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
#
select distinct ?pub ?actor 
where {
  {
    # the one particular Peter Fischer
    bind(<http://d-nb.info/gnd/12973022X> as ?actor)
    ?pub dcterms:creator  ?actor.
  } union {
    ?pub dc:creator "Fischer, Peter" .
  }
}
