# List "time series" datasets published in 2015 and their provider
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
Prefix bib:<http://id.loc.gov/ontologies/bibframe/>
Select ?title ?providerLabel
Where {
  Graph ?graph { ?s a bib:Dataset ;
                    edm:provider ?aProvider ;
                    dcterms:subject ?subjectTerm ;
                    dcterms:title ?title ;
                    dcterms:date ?publicationDate.

    			?aProvider rdfs:label ?providerLabel .
    	Filter(regex(?subjectTerm, "time series"))
    	Filter(YEAR(?publicationDate) = 2015).
  }
}