# Duplicate names (only current corporate bodies, w/o successor)
#
PREFIX gndo:    <http://d-nb.info/standards/elementset/gnd#>
PREFIX :        <http://d-nb.info/gnd/>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
#
SELECT (str(COUNT(DISTINCT ?corp)) AS ?count) ?corpName (group_concat(?corp; separator = ' | ') as ?corpBodies)
WHERE {
  ?corp gndo:preferredNameForTheCorporateBody ?corpName .
  FILTER NOT EXISTS {
    ?corp gndo:succeedingCorporateBody []
  }
}
GROUP BY ?corpName
HAVING (?count > 1)
ORDER BY DESC(?count) ?corpName
