PREFIX gnd:     <http://d-nb.info/standards/elementset/gnd#>
PREFIX :        <http://d-nb.info/gnd/>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?corpName (COUNT(DISTINCT ?corp) AS ?corpCount)
WHERE {
  ?corp gnd:preferredNameForTheCorporateBody ?corpName .
}
GROUP BY ?corpName
HAVING (?corpCount > 1)
ORDER BY DESC(?corpCount)

